module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/DQ1rvC2gXxdBwxhE1bb7h4',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/90nt5c.jpg',
    NEWSLETTER_JID: '120363402507750390@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'KAISEN-MINI',
    OWNER_NAME: 'KAISEN👑',
    OWNER_NUMBER: '50941091397',
    BOT_VERSION: '1.0.1',
    BOT_FOOTER: '> POWERED BY KAISEN 👑',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb28kDP6buMQ3EthyD3y',
};
